version: '2.3'

services:
  samba_init:
    extends:
      file: docker-compose.samba.yml
      service: samba_init
  samba_serv:
    extends:
      file: docker-compose.samba.yml
      service: samba_serv

  golang_init:
    extends:
      file: docker-compose.golang.yml
      service: golang_init
